spring:
  cloud:
    gateway:
      routes:
#--------------------------HOTEL-------------------------
#----------ADMINS
        - id: hotel-microservice-admins
          uri: lb://MICROSERVICE-HOTEL
          predicates:
            - Path=/hotel/insert, /hotel/delete, /hotel/update
          filters:
            - AdminFilter
#----------USERS
        - id: hotel-microservice-public
          uri: lb://MICROSERVICE-HOTEL
          predicates:
            - Path=/hotel/byId, /hotel/byName, /hotel/byCity, /hotel/byRoom, /hotel/byPrice
          filters:
            - UserAndAdminFilter

#--------------------------FLIGHT-------------------------
#----------TICKETS-ADMINS
        - id: flight-microservice-admins
          uri: lb://MICROSERVICE-FLIGHT
          predicates:
            - Path=/ticket/**
          filters:
            - AdminFilter
#----------AIRPLANE-ADMINS
        - id: flight-microservice-admins
          uri: lb://MICROSERVICE-FLIGHT
          predicates:
            - Path=/airplane/**
          filters:
            - AdminFilter
#----------AIRPORT-ADMINS
        - id: flight-microservice-admins
          uri: lb://MICROSERVICE-FLIGHT
          predicates:
            - Path=/airport/**
          filters:
            - AdminFilter

#--------------------------USER-JWT-------------------------
#----------ADMINS
        - id: microservice-user-jwt-admins
          uri: lb://MICROSERVICE-USER-JWT
          predicates:
            - Path=/user/byId, /user/byEmail, /user/byName, /user/delete
          filters:
            - AdminFilter
#----------USERS
        - id: microservice-user-jwt-public
          uri: lb://MICROSERVICE-USER-JWT
          predicates:
            - Path=/user/insert, /user/updateInfo
          filters:
            - UserAndAdminFilter
#----------USERS
        - id: microservice-user-jwt-auth
          uri: lb://MICROSERVICE-USER-JWT
          predicates:
            - Path=/auth/**
          filters:
            - UserAndAdminFilter
    config:
      enabled: false
  config:
    import: vault://
server:
  port: 8080

eureka:
  instance:
    instance-id: gateway

logging:
  level:
    org:
      springframework:
        vault: DEBUG
        web: DEBUG
        cloud:
          vault: DEBUG